import Head from "next/head";
import Image from "next/image";
import ButtonCreateERC721 from "../src/components/ButtonCreateERC721";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Hyperstructures</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Hyperstructures</h1>
        <p>(on Polygon & ETH)</p>

        <p className={styles.description}>
          Get started by deploying your own smart contract.
        </p>
        <ButtonCreateERC721 />

        <div className={styles.grid}>
          <a
            href="https://faucet.polygon.technology/"
            className={styles.card}
            target="__blank"
          >
            <h2>Polygon Faucet &rarr;</h2>
            <p>Get free Mumbai MATIC.</p>
          </a>

          <a
            href="https://rinkebyfaucet.com/"
            target="__blank"
            className={styles.card}
          >
            <h2>Rinkeby Faucet</h2>
            <p>Get free Rinkeby ETH.</p>
          </a>

          <a
            href="https://rinkebyfaucet.com/"
            target="__blank"
            className={styles.card}
          >
            <h2>Open Source</h2>
            <p>View code on Github.</p>
          </a>

          <a
            href="https://jacob.energy/hyperstructures.html"
            target="__blank"
            className={styles.card}
          >
            <h2>Hyperstructures</h2>
            <p>Learn more.</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
